import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {I18nextProvider} from "react-i18next";
import i18n from "i18next";
import {Providers} from "@/app/providers";
import TranslationToggle from "@/components/ToggleTranslationButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="absolute top-4 right-4 z-50">
        <TranslationToggle/>
      </div>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
